<?php

$reviews = $this->execute(); ?>
<?php if ($reviews):?>
    <h1>What people are saying about us:</h1>
<table class="table">
    <?php foreach ($reviews as $review): ?>
        <tr>
            <td><?= $block->escapeHtml($review->getCustomerName()) ?></td>
            <td><?= $block->escapeHtml($review->getTitle()) ?></td>
            <td><?= $block->escapeHtml($review->getReview()) ?></td>
        </tr>
    <?php endforeach; ?>
</table>
<?php endif;
