<?php
/**
 * @var \Inchoo\StoreReview\Block\Create $block
 */
if($block->execute()->getId()):
?>
    <p>You already created a store review</p>
    <div class="primary">
        <a class="action" href="/storereview/index/edit"><span><?= $block->escapeHtmlAttr(__('Edit your store review')) ?></span></a>
    </div>

<?php else: ?>
<form class="form"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="store-review-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Write a store review')) ?></span></legend><br />
        <div class="field note no-label"><?= $block->escapeHtml(__('Please write your store review in the fields below')) ?></div>
        <div class="field title required">
            <label class="label" for="title"><span><?= $block->escapeHtml(__('Title')) ?></span></label>
            <div class="control">
                <input name="title" id="title" title="<?= $block->escapeHtmlAttr(__('Title')) ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="review"><span><?= $block->escapeHtml(__('Review')) ?></span></label>
            <div class="control">
                <textarea name="review" id="review" title="<?= $block->escapeHtmlAttr(__('Review')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
<?php endif; ?>
