<?php
/**
 * @var \Inchoo\StoreReview\Block\Edit $block
 */
$data = $this->execute();
?>
<form class="form"
      action="<?= $block->escapeUrl($block->getUrl('storereview/index/editpost', ['_secure' => true])) ?>"
      id="store-review-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Write a store review')) ?></span></legend><br />
        <div class="field note no-label"><?= $block->escapeHtml(__('Please write your store review in the fields below')) ?></div>
        <div class="field title required">
            <label class="label" for="title"><span><?= $block->escapeHtml(__('Title')) ?></span></label>
            <div class="control">
                <input name="title" id="title" title="<?= $block->escapeHtmlAttr(__('Title')) ?>" value="<?= $block->escapeHtml($data->getTitle()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="review"><span><?= $block->escapeHtml(__('Review')) ?></span></label>
            <div class="control">
                <textarea name="review" id="review" title="<?= $block->escapeHtmlAttr(__('Review')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($data->getReview()) ?></textarea>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action" href="<?= $block->escapeUrl($block->getUrl('storereview/index/delete', ['review_id' => $block->escapeHtml($data->getReviewId())])) ?>"><span><?= $block->escapeHtmlAttr(__('Delete review')) ?></span></a>
        </div>
    </div>
</form>
